name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Download submodules
      shell: bash
      working-directory: ${{github.workspace}}
      run: | 
        git submodule init
        git submodule update
        
    - name: Download and install SDL2 v2.0.14
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        wget -c https://www.libsdl.org/release/SDL2-2.0.14.tar.gz -O - | tar -xz
        cd SDL2-2.0.14/
        mkdir build && cd build/
        ../configure
        make
        sudo make install
        sdl2-config --version

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
