name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download submodules
      shell: bash
      working-directory: ${{github.workspace}}
      run: | 
        git submodule init
        git submodule update
        
    - name: Download SDL2
      shell: bash
      working-directory: ${{github.workspace}}
      run: sudo apt install libsdl2-dev

    - name: Generate Makefile
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake -B build/ -S .
    
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: make
